### PR TITLE
Fix https://github.com/LabVIEW-DCAF/TagEditorCore/issues/328

### PR DESCRIPTION
**Pull request by dbendele**

### CODE REVIEW

**Comment by theSloopJohnB** [comment]
Test Comment. Ignore this. Sorry Doug!

**Comment by theSloopJohnB** [comment]
Bleep bloop!

LabVIEW Diff Robot here with some diffs served up hot for your pull request.

Notice something funny? Help fix me on [my GitHub repo.](https://github.com/theSloopJohnB/LabVIEW-Diff)


### control module editor.lvclass--read formatted default value.vi.png: capture

### GraphViz Mapping Visualizer.lvlib--Read Formatted Default Value.vi.png: capture

### Table Manager.lvlib--format mapping column info.vi.png: capture

**Comment by pollockm** [comment]
Niiiiiiiice

**Comment by theSloopJohnB** [comment]
Bleep bloop!

LabVIEW Diff Robot here with some diffs served up hot for your pull request.

Notice something funny? Help fix me on [my GitHub repo.](https://github.com/LabVIEW-DCAF/buildsystem)


### control module editor.lvclass--read formatted default value.vi.png: capture

### GraphViz Mapping Visualizer.lvlib--Read Formatted Default Value.vi.png: capture

### Table Manager.lvlib--format mapping column info.vi.png: capture

**Comment by theSloopJohnB** [comment]
Bleep bloop!

LabVIEW Diff Robot here with some diffs served up hot for your pull request.

Notice something funny? Help fix me on [my GitHub repo.](https://github.com/LabVIEW-DCAF/buildsystem)


### control module editor.lvclass--read formatted default value.vi.png: capture

### Format Numeric String.vi.png: capture

### GraphViz Mapping Visualizer.lvlib--Read Formatted Default Value.vi.png: capture

### Table Manager.lvlib--format mapping column info.vi.png: capture

**Comment by theSloopJohnB** [comment]
Bleep bloop!

LabVIEW Diff Robot here with some diffs served up hot for your pull request.

Notice something funny? Help fix me on [my GitHub repo.](https://github.com/LabVIEW-DCAF/buildsystem)


### control module editor.lvclass--read formatted default value.vi.png: capture

### Format Numeric String.vi.png: capture

### GraphViz Mapping Visualizer.lvlib--Read Formatted Default Value.vi.png: capture

### Table Manager.lvlib--format mapping column info.vi.png: capture

**Comment by theSloopJohnB** [comment]
Bleep bloop!

LabVIEW Diff Robot here with some diffs served up hot for your pull request.

Notice something funny? Help fix me on [my GitHub repo.](https://github.com/LabVIEW-DCAF/buildsystem)


### control module editor.lvclass--read formatted default value.vi.png: capture

### Format Numeric String.vi.png: capture

### GraphViz Mapping Visualizer.lvlib--Read Formatted Default Value.vi.png: capture

### Table Manager.lvlib--format mapping column info.vi.png: capture

**Comment by theSloopJohnB** [comment]
Bleep bloop!

LabVIEW Diff Robot here with some diffs served up hot for your pull request.

Notice something funny? Help fix me on [my GitHub repo.](https://github.com/LabVIEW-DCAF/buildsystem)


### control module editor.lvclass--read formatted default value.vi.png: capture

### Format Numeric String.vi.png: capture

### GraphViz Mapping Visualizer.lvlib--Read Formatted Default Value.vi.png: capture

### Table Manager.lvlib--format mapping column info.vi.png: capture

**Pull request merged**
