### PR TITLE
Fixes table initialization and removal to set selected index to -1

### LINKED ISSUE #103: Error on trying to remove a channel that doesn't exist
To reproduce: 

1. Create a new dynamic module. 
2. Load the DCAF standard editor
3. Go to the channel list - the "Remove channel" button is clickable
4. Click the remove channel button - throws an error since there is no check to see if the item to remove is valid

If the channel list is empty on a dynamic module, there is no check for "no valid item selected" when you click the 'remove channel' button - so it throws an error. Should either disable the button if no items is selected, or do a check on removal that there is an item selected before there is an attempt to remove it from the tree.

### LINKED ISSUE #355: Index incorrectly set to 0 at init and after removing to 0 channels.
Causes of these issues, https://github.com/LabVIEW-DCAF/DCAF-Project-Templates/issues/103, https://github.com/LabVIEW-DCAF/Scan-Engine-Module/issues/46

Original attempt to fix in this PR: https://github.com/LabVIEW-DCAF/Scan-Engine-Module/pull/47

### PR DESCRIPTION
**Pull request by theSloopJohnB**
fixes #355 
fixes https://github.com/LabVIEW-DCAF/DCAF-Project-Templates/issues/103

This issue has made it into many of our modules through the dynamic template. This will fix that problem at the root cause.

Using fixes Matt pointed out in this PR: https://github.com/LabVIEW-DCAF/Scan-Engine-Module/pull/47

### CODE REVIEW

**Comment by theSloopJohnB** [comment]
Note for reviewers - the diff robot only shows one VI. For some reason LabVIEW is crashing while creating the other one. The VI above fixes the remove down to 0 case. The other VI is the init case which sets the index to -1 on initialization, so nothing is selected at first.

**Comment by theSloopJohnB** [comment]
There was some kind of issue with the VIP file. I rebased onto master and triggered a rebuild that will hopefully fix the issue.

**Review by dbendele — COMMENTED** [review]
thanks for rebuilding the package!

changes behave great

Recommend block diagram comment in init VI to explain that MC Listbox value signaling property must be set after event registration

**Review by dbendele — APPROVED** [review]
thanks for adding comment

**Comment by gcodetechnology** [comment]
See issue #402 that was caused by this fix.

**Pull request merged**
