### PR TITLE
Fix252

### LINKED ISSUE #252: Control Module Script Fails if Clusters are Modified From Default After Sample Project Creation
This is because the original sample project will add a True to the 'Get Data Definition' VI and 'Get Index Definition'. These have to be changed manually if data is added to a method that was originally blank (or made blank when it originally had data).

A solution could be to see if these are set to False, but the clusters were changed to something other than ‘fmwk_placeholder’. The script could then also modify the data and index definitions appropriately.

Originally created in templates Control Module Script Fails if Clusters are Modified From Default After Sample Project Creation #38

### PR DESCRIPTION
**Pull request by becega**
Fixes #252

### CODE REVIEW

**Comment by theSloopJohnB** [comment]
There's a new subVI in FromClusterToTagBusScript that I'm not sure of the purpose:

image

It looks like it's just a pass through. Did you mean to include it?

Otherwise the change looks good to me.

**Comment by becega** [comment]
@theSloopJohnB Fixed

**Comment by theSloopJohnB** [comment]
Looks good!

**Comment by theSloopJohnB** [comment]
I merged in the latest from master at GitHub's request - it has a VI not touched in this branch. I'll wait for the build to finish and then merge.

**Comment by theSloopJohnB** [comment]
Build six failed because a file was still open when LabVIEW tried to delete it. I opened the build machine and saw that VIPM was running. I closed it and re-ran the build - success! I'll merge the change now.

**Pull request merged**
